name: CI Self-Heal

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

jobs:
  rerun-on-failure:
    if: >-
      ${{ github.event.workflow_run.conclusion == 'failure' && github.event.workflow_run.run_attempt < 3 }}
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Trigger CI rerun (attempt ${{ github.event.workflow_run.run_attempt + 1 }})
        uses: actions/github-script@v7
        with:
          script: |
            const runId = context.payload.workflow_run.id;
            core.info(`Re-running CI for run ${runId} (attempt ${context.payload.workflow_run.run_attempt + 1})`);
            await github.request('POST /repos/{owner}/{repo}/actions/runs/{run_id}/rerun', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: runId,
            });
