name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

defaults:
  run:
    shell: bash

jobs:
  linux:
    runs-on: ubuntu-latest
    container:
      image: swift:6.1-jammy
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # No SDL provisioning needed for headless tests
      - name: Prepare build env (headless)
        run: |
          echo "Preparing headless CI build (no SDL install)"
      - name: Cache Swift build artifacts
        uses: actions/cache@v4
        with:
          path: |
            .build
            /github/home/.swiftpm
          key: ${{ runner.os }}-swift-6.1-jammy-build-${{ hashFiles('Package.swift', 'Sources/**', 'Tests/**') }}
          restore-keys: |
            ${{ runner.os }}-swift-6.1-jammy-build-

      - name: Cache shader artifacts
        uses: actions/cache@v4
        with:
          path: Sources/SDLKit/Generated
          key: ${{ runner.os }}-shader-${{ hashFiles('Shaders/**', 'Plugins/ShaderBuildPlugin/**', 'Scripts/ShaderBuild/**') }}
          restore-keys: |
            ${{ runner.os }}-shader-

      - name: Build shader bundle (best effort)
        run: |
          python3 Scripts/ShaderBuild/build-shaders.py "$PWD" .build/shader-cache
        continue-on-error: true

      - name: Build and test
        env:
          SDLKIT_GUI_ENABLED: 'false'
        run: |
          # Build and test with HEADLESS_CI to avoid linking SDL3
          swift build -v -Xswiftc -DHEADLESS_CI
          swift test -v -Xswiftc -DHEADLESS_CI
