name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        swift: [ '6.1-jammy' ]
    container:
      image: swift:${{ matrix.swift }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build tools
        run: |
          apt-get update
          apt-get install -y --no-install-recommends git cmake ninja-build pkg-config ca-certificates
      - name: Install or provision SDL3
        run: |
          set -euxo pipefail
          if pkg-config --exists sdl3; then
            echo "SDL3 found via pkg-config"
          else
            if apt-get install -y --no-install-recommends libsdl3-dev; then
              echo "Installed libsdl3-dev from apt"
            else
              echo "libsdl3-dev not available; building SDL fork (console mode)"
              git clone --depth 1 https://github.com/Fountain-Coach/SDL.git SDL-fork
              cmake -S SDL-fork -B SDL-fork/build \
                -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/local \
                -DSDL_TESTS=OFF -DSDL_INSTALL_TESTS=OFF \
                -DSDL_SHARED=ON -DSDL_STATIC=OFF \
                -DSDL_UNIX_CONSOLE_BUILD=ON \
                -G Ninja
              cmake --build SDL-fork/build --target install
              echo "PKG_CONFIG_PATH=${{ github.workspace }}/local/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV
              echo "SDL3_INCLUDE_DIR=${{ github.workspace }}/local/include" >> $GITHUB_ENV
              echo "SDL3_LIB_DIR=${{ github.workspace }}/local/lib" >> $GITHUB_ENV
              echo "LD_LIBRARY_PATH=${{ github.workspace }}/local/lib:${LD_LIBRARY_PATH:-}" >> $GITHUB_ENV
            fi
          fi
      - name: Cache Swift build artifacts
        uses: actions/cache@v4
        with:
          path: |
            .build
            /github/home/.swiftpm
          key: ${{ runner.os }}-swift-${{ matrix.swift }}-build-${{ hashFiles('Package.swift', 'Sources/**', 'Tests/**') }}
          restore-keys: |
            ${{ runner.os }}-swift-${{ matrix.swift }}-build-

      # Build SDL fork with minimal features into a local prefix (no sudo)
      - name: Build and test
        env:
          SDLKIT_GUI_ENABLED: 'false'
          SDL3_INCLUDE_DIR: ${{ env.SDL3_INCLUDE_DIR }}
          SDL3_LIB_DIR: ${{ env.SDL3_LIB_DIR }}
          PKG_CONFIG_PATH: ${{ env.PKG_CONFIG_PATH }}
          LD_LIBRARY_PATH: ${{ env.LD_LIBRARY_PATH }}
        run: |
          swift build -v
          swift test -v
