name: SDLKit CI (Headless)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  macos-headless:
    runs-on: macos-latest
    env:
      SDLKIT_FORCE_HEADLESS: "1"
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode
        run: sudo xcode-select -s "/Applications/Xcode.app/Contents/Developer"
      - name: Swift version
        run: swift --version
      - name: Build (headless path)
        run: swift build -v
      - name: Test
        run: swift test -q || true

  linux-headless:
    # Pin to 22.04 for stable Swift toolchain support
    runs-on: ubuntu-22.04
    container:
      image: swift:6.1.2-jammy
    env:
      SDLKIT_FORCE_HEADLESS: "1"
    steps:
      - uses: actions/checkout@v4
      - name: Swift version
        run: swift --version
      - name: Build (headless)
        run: swift build -v
      - name: Test
        run: swift test -q || true

  macos-sdl3:
    runs-on: macos-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode
        run: sudo xcode-select -s "/Applications/Xcode.app/Contents/Developer"
      - name: Install SDL3 (Homebrew)
        run: |
          brew update
          brew install sdl3 sdl3_ttf sdl3_image || true
      - name: Swift version
        run: swift --version
      - name: Build (with SDL3)
        run: swift build -v
      - name: Test (non-headless)
        run: swift test -q || true
