name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  linux:
    runs-on: ubuntu-latest
    container:
      image: swift:5.10-jammy
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build tools
        run: |
          apt-get update
          apt-get install -y --no-install-recommends git cmake ninja-build pkg-config ca-certificates

      # Build SDL fork with minimal features into a local prefix (no sudo)
      - name: Build SDL fork (minimal)
        run: |
          git clone --depth 1 https://github.com/Fountain-Coach/SDL.git SDL-fork
          cmake -S SDL-fork -B SDL-fork/build \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/local \
            -DSDL_TESTS=OFF -DSDL_INSTALL_TESTS=OFF -DSDL_DISABLE_INSTALL_DOCS=ON \
            -DSDL_SHARED=ON -DSDL_STATIC=OFF \
            -DSDL_VIDEO=OFF -DSDL_AUDIO=OFF -DSDL_RENDER=OFF -DSDL_SAMPLES=OFF \
            -G Ninja
          cmake --build SDL-fork/build --target install

      - name: Build and test
        env:
          SDLKIT_GUI_ENABLED: 'false'
          SDL3_INCLUDE_DIR: ${{ github.workspace }}/local/include
          SDL3_LIB_DIR: ${{ github.workspace }}/local/lib
          PKG_CONFIG_PATH: ${{ github.workspace }}/local/lib/pkgconfig
        run: |
          swift build -v
          swift test -v
