name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake ninja-build pkg-config

      - name: Setup Swift
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: '5.10'

      - name: Build SDL fork
        run: |
          git clone --depth 1 https://github.com/Fountain-Coach/SDL.git SDL-fork
          cmake -S SDL-fork -B SDL-fork/build -DCMAKE_BUILD_TYPE=Release -DSDL_TESTS=OFF -DSDL_SHARED=ON -DSDL_STATIC=OFF -G Ninja
          sudo cmake --build SDL-fork/build --target install
          echo "PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV

      - name: Build and test
        env:
          SDLKIT_GUI_ENABLED: 'false'
        run: |
          swift build -v
          swift test -v

  macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Swift
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: '5.10'

      - name: Install CMake
        run: |
          brew update
          brew install cmake ninja pkg-config

      - name: Build SDL fork
        run: |
          git clone --depth 1 https://github.com/Fountain-Coach/SDL.git SDL-fork
          cmake -S SDL-fork -B SDL-fork/build -DCMAKE_BUILD_TYPE=Release -DSDL_TESTS=OFF -DSDL_SHARED=ON -DSDL_STATIC=OFF -G Ninja
          sudo cmake --build SDL-fork/build --target install
          echo "PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV

      - name: Build and test
        env:
          SDLKIT_GUI_ENABLED: 'false'
        run: |
          swift build -v
          swift test -v

