name: SDLKit CI (Headless)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  macos-headless:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode
        run: sudo xcode-select -s "/Applications/Xcode.app/Contents/Developer"
      - name: Swift version
        run: swift --version
      - name: Build (headless path)
        run: swift build -v
      - name: Test
        run: swift test -q || true

  linux-headless:
    runs-on: ubuntu-latest
    env:
      SDLKIT_FORCE_HEADLESS: "1"
    steps:
      - uses: actions/checkout@v4
      - name: Install Swift
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: "6.1.2"
      - name: Swift version
        run: swift --version
      - name: Build (headless)
        run: swift build -v
      - name: Test
        run: swift test -q || true
