name: SDLKit OpenAPI

on:
  push:
    branches: [ main ]
    paths:
      - 'Sources/SDLKitAPI/**'
      - '.github/workflows/openapi.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'Sources/SDLKitAPI/**'
      - '.github/workflows/openapi.yml'

jobs:
  openapi-build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode
        run: sudo xcode-select -s "/Applications/Xcode.app/Contents/Developer"
      - name: Swift version
        run: swift --version
      - name: Build OpenAPI target (codegen)
        run: swift build -v --target SDLKitAPI

